# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a994c8084de5e6f90871f72831a285adb25cb19ee9e1827804a19ae8498b32f529c1acc65284340134e37df88be0f3854eaa3692e272979d0449cf53c7f34ba

test:
  secret_key_base: 7a58858d8cf912d2204837e24ea8ff6d4c2e3128632aacf0394b9f3c66918183571b94b8b78e6f313e6a41a5d10c738f2074a7a63e14bb2b285c45efc6bc783e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
